const path = require('path');

module.exports = {
  args: {
    PPD_ROOT: 'tests',
    PPD_ROOT_ADDITIONAL: [path.join(__dirname, './src/Plugins')],
    PPD_FILES_IGNORE: 'tests\\broken.yaml',
    PPD_LIFE_CYCLE_FUNCTIONS: ['beforeRun', 'beforeTest', 'run', 'runTest', 'afterRun', 'afterTest'],
    PPD_ALIASES: {
      data: ['d', '📋'],
      bindData: [
        'bD',
        'bd',
        '📌📋',
        'dataBind',
        'db',
        'dB',
        'dataFunction',
        'dF',
        'df',
        '🔑📋',
        'functionData',
        'fd',
        'fD',
      ],
      selectors: ['selector', 's', '💠'],
      bindSelectors: [
        'bindSelector',
        'bS',
        'bs',
        '📌💠',
        'selectorBind',
        'selectorsBind',
        'sb',
        'sB',
        'selectorsFunction',
        'selectorFunction',
        'sF',
        'sf',
        '🔑💠',
        'functionSelector',
        'functionSelectors',
        'fs',
        'fS',
      ],
      bindResults: [
        'bindResult',
        'bR',
        'br',
        'result',
        'results',
        'r',
        '↩️',
        'R',
        'rb',
        'rB',
        'resultBind',
        'resultsBind',
        'rF',
        'rf',
        '🔑↩️',
        'functionResult',
        'fr',
        'fR',
        'resultFunction',
        'values',
        'value',
        'v',
        'var',
        'vars',
        'const',
        'c',
        'let',
        'set',
      ],
      options: ['option', 'opt', 'o', '⚙️'],
    },
    // PPD_LOG_STEPID: true,
  },
};
