export type Colors = {
  sane: number;
  black: number;
  red: number;
  green: number;
  yellow: number;
  blue: number;
  magenta: number;
  cyan: number;
  white: number;
  raw?: number;
  timer?: number;
  debug?: number;
  info?: number;
  test?: number;
  warn?: number;
  error?: number;
  trace?: number;
  env?: number;
};
